---
- name: postfix - Include "configure_{{ ansible_pkg_mgr }}.yml"
  include_tasks: "{{ item }}"
  loop: "{{ query('first_found', params) }}"
  vars:
    params:
      files:
        - configure_{{ ansible_pkg_mgr }}.yml
      skip: true

- name: postfix - Install postfix
  package:
    name: postfix

- name: postfix - Configure /etc/postfix/main.cf
  template:
    src: etc/postfix/main.cf
    dest: "{{ _postfix_main_cf }}"
    mode: 0444
    owner: root
    group: root
  register: _postfix_etc_postfix_main_cf

- name: postfix - Configure /etc/postfix/master.cf
  template:
    src: etc/postfix/master.cf
    dest: "{{ _postfix_master_cf }}"
    mode: 0444
    owner: root
    group: root
  register: _postfix_etc_postfix_master_cf

- name: postfix - Configure postmap from `postfix_postmap`
  template:
    src: "{{ item.value }}"
    dest: "{{ item.key }}"
    mode: 0444
    owner: root
    group: root
  loop: "{{ postfix_postmap | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  register: _postfix_postmap_template

- name: postfix - Execute postmap command  # noqa no-handler
  command: /usr/sbin/postmap "{{ item.item.key }}"
  when: item is changed
  loop: "{{ _postfix_postmap_template.results }}"
  loop_control:
    label: "{{ item.item.key }}"

- name: postfix - Configure postaliases from `postfix_postalias`
  template:
    src: "{{ item.value }}"
    dest: "{{ item.key }}"
    mode: 0444
    owner: root
    group: root
  loop: "{{ postfix_postalias | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  register: _postfix_postalias_template

- name: postfix - Execute postalias command  # noqa no-handler
  command: /usr/sbin/postalias "{{ item.item.key }}"
  when: item is changed
  loop: "{{ _postfix_postalias_template.results }}"
  loop_control:
    label: "{{ item.item.key }}"

- name: postfix - Enable systemd service
  systemd:
    name: postfix.service
    enabled: true
    state: "{{ ((_postfix_etc_postfix_main_cf is changed) or (_postfix_etc_postfix_master_cf is changed)) | ternary('restarted', 'started') }}"
