---
dependency:
  name: galaxy
driver:
  name: ec2
lint: |
  set -e
  yamllint -c molecule/shared/.yamllint.yml .
  ansible-lint --exclude molecule
  flake8 --config molecule/shared/.flake8.conf
platforms:
  # https://wiki.debian.org/Cloud/AmazonEC2Image/Stretch
  - name: stretch
    ami_owner: 379101102735
    ami_name_regexp: "debian-stretch-hvm-x86_64-gp2-*"
    instance_type: t3.micro
  # https://wiki.debian.org/Cloud/AmazonEC2Image/Buster
  - name: buster
    ami_owner: 136693071363
    ami_name_regexp: "debian-10-amd64-*-10"
    instance_type: t3.micro
provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "true"
  config_options:
    defaults:
      interpreter_python: /usr/bin/python3
verifier:
  name: testinfra
  options:
    verbose: true
    sudo: true
