---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: false
  vars:
    ssh_user: admin
    ssh_port: 22
    security_group_name: molecule
    security_group_description: Security group for testing Molecule
    security_group_rules:
      - proto: tcp
        from_port: "{{ ssh_port }}"
        to_port: "{{ ssh_port }}"
        cidr_ip: '0.0.0.0/0'
      - proto: icmp
        from_port: 8
        to_port: -1
        cidr_ip: '0.0.0.0/0'
    security_group_rules_egress:
      - proto: -1
        from_port: 0
        to_port: 0
        cidr_ip: '0.0.0.0/0'

    keypair_name: "molecule_key_{{ 20|random(seed=(lookup('env', 'CI_JOB_ID') ~ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY'))) }}"
    keypair_path: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key"
  tasks:
    - name: Create security group
      ec2_group:
        name: "{{ security_group_name }}"
        description: "{{ security_group_name }}"
        rules: "{{ security_group_rules }}"
        rules_egress: "{{ security_group_rules_egress }}"

    - name: Test for presence of local keypair
      stat:
        path: "{{ keypair_path }}"
      register: keypair_local

    - name: Delete remote keypair
      ec2_key:
        name: "{{ keypair_name }}"
        state: absent
      when: not keypair_local.stat.exists

    - name: Create keypair
      ec2_key:
        name: "{{ keypair_name }}"
      register: keypair

    - name: Persist the keypair
      copy:
        dest: "{{ keypair_path }}"
        content: "{{ keypair.key.private_key }}"
        mode: 0600
      when: keypair.changed

    - name: Found AMI based on filters
      ec2_ami_info:
        owners: ["{{ item.ami_owner }}"]
        filters:
          name: "{{ item.ami_name_regexp }}"
      register: ami_facts
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Create molecule instance(s)
      ec2:
        key_name: "{{ keypair_name }}"
        image: "{{ (item.images | sort(attribute='creation_date') | last)['image_id'] }}"
        instance_type: "{{ item.item.instance_type }}"
        vpc_subnet_id: "{{ item.item.vpc_subnet_id | default(lookup('env', 'VPC_SUBNET_ID')) }}"
        group: "{{ security_group_name }}"
        instance_tags:
          instance: "{{ item.item.name }}"
          owner: oxalide.saas_tech@fr.clara.net
        wait: true
        assign_public_ip: true
        exact_count: 1
        count_tag:
          instance: "{{ item.item.name }}"
          created_by: "molecule"
      register: server
      loop: "{{ ami_facts.results }}"
      loop_control:
        label: "{{ item.item.name }}"
      async: 7200
      poll: 0

    - name: Wait for instance(s) creation to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: ec2_jobs
      until: ec2_jobs.finished
      retries: 300
      loop: "{{ server.results }}"
      loop_control:
        label: "{{ item.item.item.name }}"

    # Mandatory configuration for Molecule to function.

    - name: Populate instance config dict
      set_fact:
        instance_conf_dict: {
          'instance': "{{ item.instances[0].tags.instance }}",
          'address': "{{ item.instances[0].public_ip }}",
          'user': "{{ ssh_user }}",
          'port': "{{ ssh_port }}",
          'identity_file': "{{ keypair_path }}",
          'instance_ids': "{{ item.instance_ids }}", }
      loop: "{{ ec2_jobs.results }}"
      loop_control:
        label: "{{ item.instances[0].tags.instance }}"
      register: instance_config_dict
      when: server.changed | bool

    - name: Convert instance config dict to a list
      set_fact:
        instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"
      when: server.changed | bool

    - name: Dump instance config
      copy:
        content: "{{ instance_conf | to_json | from_json | to_yaml }}"
        dest: "{{ molecule_instance_config }}"
        mode: 0644
      when: server.changed | bool

    - name: Wait for SSH
      wait_for:
        port: "{{ ssh_port }}"
        host: "{{ item.address }}"
        search_regex: SSH
        delay: 10
        timeout: 300
      loop: "{{ lookup('file', molecule_instance_config) | from_yaml }}"
      loop_control:
        label: "{{ item.instance }}"
